# Generated by Django 3.2.6 on 2021-08-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_photo'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='categoryblood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.categoryblood'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.religion'),
        ),
    ]
